name: Create and publish Docker Images

on:
  push:
    branches: ['master']
    paths:
      - 'poky-mistysom-sdk.Dockerfile'
      - 'poky-mistysom-sdk-meson.Dockerfile'
      - 'rzv_drp-ai_tvm.Dockerfile'
      - '.github/workflows/deploy-image.yml'
  workflow_dispatch:
    inputs:
      build_sdk:
        description: 'Build SDK image'
        required: false
        default: false
        type: boolean
      build_meson:
        description: 'Build Meson image'
        required: false
        default: false
        type: boolean
      build_rzv_tvm:
        description: 'Build RZV TVM image'
        required: false
        default: false
        type: boolean
      build_all:
        description: 'Build all images (overrides individual selections)'
        required: false
        default: false
        type: boolean

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: mistysom/poky-mistysom-sdk
  POKY_VERSION: 3.1.31

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      sdk: ${{ steps.filter.outputs.sdk || github.event.inputs.build_sdk == 'true' || github.event.inputs.build_all == 'true' }}
      meson: ${{ steps.filter.outputs.meson || github.event.inputs.build_meson == 'true' || github.event.inputs.build_all == 'true' }}
      rzv-tvm: ${{ steps.filter.outputs.rzv-tvm || github.event.inputs.build_rzv_tvm == 'true' || github.event.inputs.build_all == 'true' }}
      is_manual: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0         # need full history for paths-filter

      - name: Filter paths
        uses: dorny/paths-filter@v2
        id: filter
        if: github.event_name != 'workflow_dispatch'
        with:
          filters: |
            sdk:
              - 'poky-mistysom-sdk.Dockerfile'
            meson:
              - 'poky-mistysom-sdk-meson.Dockerfile'
            rzv-tvm:
              - 'rzv_drp-ai_tvm.Dockerfile'

      - name: Manual trigger summary
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Manual workflow triggered with:"
          echo "Build SDK: ${{ github.event.inputs.build_sdk }}"
          echo "Build Meson: ${{ github.event.inputs.build_meson }}"
          echo "Build RZV TVM: ${{ github.event.inputs.build_rzv_tvm }}"
          echo "Build All: ${{ github.event.inputs.build_all }}"

  build-poky-mistysom-sdk:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.sdk == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: poky-mistysom-sdk.Dockerfile
          push: true
          pull: true
          tags: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.POKY_VERSION }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"

  build-poky-mistysom-sdk-meson:
    needs:
      - detect-changes
      - build-poky-mistysom-sdk
    if: |
      always() &&
      (
        (needs.detect-changes.outputs.sdk == 'true' && needs.build-poky-mistysom-sdk.result == 'success') ||
        (needs.build-poky-mistysom-sdk.result == 'skipped' && needs.detect-changes.outputs.meson == 'true')
      )
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: poky-mistysom-sdk-meson.Dockerfile
          push: true
          pull: true
          tags: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.POKY_VERSION }}-meson"

  build-rzv-drp-ai-tvm:
    needs:
      - detect-changes
      - build-poky-mistysom-sdk
    if: |
      always() &&
      (
        (needs.detect-changes.outputs.sdk == 'true' && needs.build-poky-mistysom-sdk.result == 'success') ||
        (needs.build-poky-mistysom-sdk.result == 'skipped' && needs.detect-changes.outputs.rzv-tvm == 'true')
      )
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: rzv_drp-ai_tvm.Dockerfile
          push: true
          pull: true
          tags: "${{ env.REGISTRY }}/mistysom/rzv-drp-ai-tvm:2.6.0,${{ env.REGISTRY }}/mistysom/rzv-drp-ai-tvm:latest"
